spring:
 security:
  oauth2:
   client:
    registration:
     google:
      clientId: enter-client-id
      clientSecret:  enter-client-secret
      scope: openid, profile, email, https://www.googleapis.com/auth/youtube

logging:
 level:
  com.example.OAuthDemo: DEBUG
  org.springframework.security: TRACE
  org.springframework.security.oaut2: TRACE
  org.springframework.web: TRACE
  org.springframework.web.reactive: TRACE